extends RefCounted

class_name SwordCatalog

const SWORD_SHEET := preload("res://Assets/Swords/File.png")
const CELL_SIZE := Vector2i(32, 32)
const DEFAULT_SWORD_NAME := "starter_sword"

const STARTER_SWORD := {
	"atlas": Vector2i(1, 2),
	"display_name": "Starter Sword",
	"description": "Dein verlaessliches Basisschwert. Solide Werte, bis du eine seltenere Klinge findest.",
	"rarity": "common",
	"attack_power_bonus": 2,
	"damage_bonus": 0.05,
	"crit_chance_bonus": 0.02,
	"crit_damage_bonus": 0.05,
	"attack_speed_bonus": 0.02,
	"attack_reach_bonus": 0.0,
	"knockback_bonus": 10.0,
	"move_speed_bonus": 0.0,
	"throw_damage": 4.0,
	"skill_id": "starter_spark",
	"skill_name": "Slime Spark",
	"skill_description": "Jeder dritte Treffer verursacht einen kleinen Extraschlag.",
}

const SHOP_ORDER := [
	"fire",
	"ice",
	"poisonous",
	"quel",
	"sun",
	"moon",
	"stars",
	"cursed_relic",
	"divine_relic",
	"rose",
	"elegant",
	"powerful",
	"electric",
	"knight",
	"wings",
	"magic",
	"fragmented",
	"nature",
	"justice",
	"many",
	"glowing",
	"dragon_slayer",
	"guardian",
	"sinister",
	"jeweled",
	"ocean",
	"flower",
	"royal",
	"ceremony",
	"ancient",
]

const SWORD_DEFS := {
	"fire": {
		"atlas": Vector2i(0, 0),
		"display_name": "Fire Sword",
		"description": "Eine glutrote Klinge, die Treffer in anhaltende Flammen verwandelt.",
		"rarity": "rare",
		"attack_power_bonus": 5,
		"damage_bonus": 0.16,
		"crit_chance_bonus": 0.04,
		"crit_damage_bonus": 0.12,
		"attack_speed_bonus": 0.0,
		"attack_reach_bonus": 0.08,
		"knockback_bonus": 18.0,
		"move_speed_bonus": 0.0,
		"throw_damage": 10.0,
		"skill_id": "fire_burn",
		"skill_name": "Ember Wake",
		"skill_description": "Treffer entzuenden Gegner und hinterlassen eine kurze Brandspur.",
	},
	"ice": {
		"atlas": Vector2i(1, 0),
		"display_name": "Ice Sword",
		"description": "Frost klafft an der Schneide und verlangsamt alles, was sie beruehrt.",
		"rarity": "rare",
		"attack_power_bonus": 4,
		"damage_bonus": 0.12,
		"crit_chance_bonus": 0.05,
		"crit_damage_bonus": 0.08,
		"attack_speed_bonus": 0.03,
		"attack_reach_bonus": 0.08,
		"knockback_bonus": 14.0,
		"move_speed_bonus": 0.0,
		"throw_damage": 9.0,
		"skill_id": "ice_shatter",
		"skill_name": "Shatter Chill",
		"skill_description": "Frosttreffer verursachen Extraschaden und bremsen Gegner sichtbar aus.",
	},
	"poisonous": {
		"atlas": Vector2i(2, 0),
		"display_name": "Poisonous Sword",
		"description": "Verdorbene Dornen sickern durch die Klinge und setzen Gift frei.",
		"rarity": "uncommon",
		"attack_power_bonus": 3,
		"damage_bonus": 0.1,
		"crit_chance_bonus": 0.03,
		"crit_damage_bonus": 0.08,
		"attack_speed_bonus": 0.04,
		"attack_reach_bonus": 0.02,
		"knockback_bonus": 8.0,
		"move_speed_bonus": 0.02,
		"throw_damage": 8.0,
		"skill_id": "poison_bloom",
		"skill_name": "Toxic Bloom",
		"skill_description": "Vergiftet Ziele und laesst mehrere kleine Schadensticks nachlaufen.",
	},
	"quel": {
		"atlas": Vector2i(3, 0),
		"display_name": "Duel Sword",
		"description": "Zwei Klingen, ein Fokus: in direkten Duellen wird jeder Schlag praeziser.",
		"rarity": "rare",
		"attack_power_bonus": 4,
		"damage_bonus": 0.1,
		"crit_chance_bonus": 0.08,
		"crit_damage_bonus": 0.12,
		"attack_speed_bonus": 0.05,
		"attack_reach_bonus": 0.06,
		"knockback_bonus": 10.0,
		"move_speed_bonus": 0.02,
		"throw_damage": 7.0,
		"skill_id": "duel_focus",
		"skill_name": "Duel Focus",
		"skill_description": "Gegen einzelne Gegner im Nahbereich steigen Schaden und Crit-Chance stark an.",
	},
	"sun": {
		"atlas": Vector2i(4, 0),
		"display_name": "Sun Sword",
		"description": "Warme Strahlen lodern an der Klinge und heilen den Schwaecheren im Kampf.",
		"rarity": "rare",
		"attack_power_bonus": 5,
		"damage_bonus": 0.13,
		"crit_chance_bonus": 0.03,
		"crit_damage_bonus": 0.12,
		"attack_speed_bonus": 0.01,
		"attack_reach_bonus": 0.06,
		"knockback_bonus": 16.0,
		"move_speed_bonus": 0.0,
		"throw_damage": 10.0,
		"skill_id": "solar_flare",
		"skill_name": "Solar Flare",
		"skill_description": "Treffer heilen Joey leicht und lassen auf Crits einen Sonnenblitz einschlagen.",
	},
	"moon": {
		"atlas": Vector2i(5, 0),
		"display_name": "Moon Sword",
		"description": "Eine stille Nachtklinge fuer schnelle Serien und dunkle Konter.",
		"rarity": "rare",
		"attack_power_bonus": 3,
		"damage_bonus": 0.09,
		"crit_chance_bonus": 0.06,
		"crit_damage_bonus": 0.16,
		"attack_speed_bonus": 0.08,
		"attack_reach_bonus": 0.03,
		"knockback_bonus": 8.0,
		"move_speed_bonus": 0.04,
		"throw_damage": 7.0,
		"skill_id": "moonstep",
		"skill_name": "Moonstep",
		"skill_description": "Treffer geben kurzzeitig Tempo und lassen Joey aus dem Schatten nachsetzen.",
	},
	"stars": {
		"atlas": Vector2i(0, 1),
		"display_name": "Stars Sword",
		"description": "Jeder Hieb wirkt wie ein Sternensplitterregen aus dem Himmel.",
		"rarity": "epic",
		"attack_power_bonus": 4,
		"damage_bonus": 0.14,
		"crit_chance_bonus": 0.06,
		"crit_damage_bonus": 0.14,
		"attack_speed_bonus": 0.03,
		"attack_reach_bonus": 0.08,
		"knockback_bonus": 12.0,
		"move_speed_bonus": 0.03,
		"throw_damage": 9.0,
		"skill_id": "starfall",
		"skill_name": "Starfall",
		"skill_description": "Jeder dritte Treffer laesst Sternensplitter auf Gegner in der Naehe niedergehen.",
	},
	"cursed_relic": {
		"atlas": Vector2i(1, 1),
		"display_name": "Cursed Relic Sword",
		"description": "Grossartige Macht, aber nie ohne Preis. Die Klinge opfert Leben fuer Gewalt.",
		"rarity": "legendary",
		"attack_power_bonus": 8,
		"damage_bonus": 0.22,
		"crit_chance_bonus": 0.06,
		"crit_damage_bonus": 0.18,
		"attack_speed_bonus": 0.02,
		"attack_reach_bonus": 0.04,
		"knockback_bonus": 24.0,
		"move_speed_bonus": -0.01,
		"throw_damage": 12.0,
		"skill_id": "blood_price",
		"skill_name": "Blood Price",
		"skill_description": "Massiver Bonus-Schaden, aber jeder Treffer kostet Joey etwas Leben.",
	},
	"divine_relic": {
		"atlas": Vector2i(2, 1),
		"display_name": "Divine Relic Sword",
		"description": "Ein heiliges Artefakt, das Smite-Energie in jeden Schlag webt.",
		"rarity": "legendary",
		"attack_power_bonus": 7,
		"damage_bonus": 0.2,
		"crit_chance_bonus": 0.06,
		"crit_damage_bonus": 0.18,
		"attack_speed_bonus": 0.02,
		"attack_reach_bonus": 0.07,
		"knockback_bonus": 18.0,
		"move_speed_bonus": 0.01,
		"throw_damage": 11.0,
		"skill_id": "divine_smite",
		"skill_name": "Divine Smite",
		"skill_description": "Crits rufen ein heiliges Nachbeben hervor und heilen Joey.",
	},
	"rose": {
		"atlas": Vector2i(3, 1),
		"display_name": "Rose Sword",
		"description": "Eine zarte Klinge mit Dornen, die Ziele aufreissen und blueten lassen.",
		"rarity": "uncommon",
		"attack_power_bonus": 3,
		"damage_bonus": 0.08,
		"crit_chance_bonus": 0.04,
		"crit_damage_bonus": 0.1,
		"attack_speed_bonus": 0.05,
		"attack_reach_bonus": 0.02,
		"knockback_bonus": 6.0,
		"move_speed_bonus": 0.03,
		"throw_damage": 7.0,
		"skill_id": "rose_bleed",
		"skill_name": "Rose Bleed",
		"skill_description": "Laesst Blueten splittern und erzeugt stapelnden Blutungsschaden.",
	},
	"elegant": {
		"atlas": Vector2i(4, 1),
		"display_name": "Elegant Sword",
		"description": "Praezision statt Brutalitaet. Ideal fuer elegante Combo-Loops.",
		"rarity": "rare",
		"attack_power_bonus": 3,
		"damage_bonus": 0.1,
		"crit_chance_bonus": 0.08,
		"crit_damage_bonus": 0.12,
		"attack_speed_bonus": 0.1,
		"attack_reach_bonus": 0.05,
		"knockback_bonus": 6.0,
		"move_speed_bonus": 0.04,
		"throw_damage": 8.0,
		"skill_id": "elegant_riposte",
		"skill_name": "Elegant Riposte",
		"skill_description": "Beschleunigt die Combo-Kette und erzeugt schnelle Nachhiebe.",
	},
	"powerful": {
		"atlas": Vector2i(5, 1),
		"display_name": "Powerful Sword",
		"description": "Eine rohe Klinge, gebaut fuer reine Gewalt und brutalen Rueckstoss.",
		"rarity": "rare",
		"attack_power_bonus": 9,
		"damage_bonus": 0.18,
		"crit_chance_bonus": 0.01,
		"crit_damage_bonus": 0.12,
		"attack_speed_bonus": -0.04,
		"attack_reach_bonus": 0.04,
		"knockback_bonus": 34.0,
		"move_speed_bonus": -0.01,
		"throw_damage": 12.0,
		"skill_id": "impact_drive",
		"skill_name": "Impact Drive",
		"skill_description": "Schwere Schlaege schieben Gegner weit weg und verursachen Bonus-Schaden.",
	},
	"electric": {
		"atlas": Vector2i(0, 2),
		"display_name": "Electric Sword",
		"description": "Geladene Funken springen an der Schneide entlang und suchen weitere Ziele.",
		"rarity": "epic",
		"attack_power_bonus": 5,
		"damage_bonus": 0.14,
		"crit_chance_bonus": 0.05,
		"crit_damage_bonus": 0.14,
		"attack_speed_bonus": 0.04,
		"attack_reach_bonus": 0.05,
		"knockback_bonus": 12.0,
		"move_speed_bonus": 0.03,
		"throw_damage": 10.0,
		"skill_id": "chain_arc",
		"skill_name": "Chain Arc",
		"skill_description": "Blitze springen vom Hauptziel auf weitere Gegner in der Umgebung ueber.",
	},
	"knight": {
		"atlas": Vector2i(1, 2),
		"display_name": "Knight Sword",
		"description": "Ein ausgewogenes Ritterschwert mit schwerer Haltung und solidem Guard.",
		"rarity": "common",
		"attack_power_bonus": 4,
		"damage_bonus": 0.1,
		"crit_chance_bonus": 0.03,
		"crit_damage_bonus": 0.08,
		"attack_speed_bonus": 0.0,
		"attack_reach_bonus": 0.03,
		"knockback_bonus": 16.0,
		"move_speed_bonus": 0.0,
		"throw_damage": 8.0,
		"skill_id": "guard_counter",
		"skill_name": "Guard Counter",
		"skill_description": "Treffer bauen eine kleine Schutzbarriere auf und verstaerken den naechsten Hieb.",
	},
	"wings": {
		"atlas": Vector2i(2, 2),
		"display_name": "Wings Sword",
		"description": "Federleicht, ideal fuer Luftkaempfe und schwebende Ketten.",
		"rarity": "rare",
		"attack_power_bonus": 3,
		"damage_bonus": 0.09,
		"crit_chance_bonus": 0.04,
		"crit_damage_bonus": 0.1,
		"attack_speed_bonus": 0.08,
		"attack_reach_bonus": 0.08,
		"knockback_bonus": 6.0,
		"move_speed_bonus": 0.06,
		"throw_damage": 7.0,
		"skill_id": "aerial_drift",
		"skill_name": "Aerial Drift",
		"skill_description": "Lufttreffer verursachen Bonus-Schaden und halten Joey kuerzer in der Luft.",
	},
	"magic": {
		"atlas": Vector2i(3, 2),
		"display_name": "Magic Sword",
		"description": "Eine arkane Klinge, die unsichtbare Nachschwinger durch den Kampf schickt.",
		"rarity": "epic",
		"attack_power_bonus": 4,
		"damage_bonus": 0.13,
		"crit_chance_bonus": 0.05,
		"crit_damage_bonus": 0.16,
		"attack_speed_bonus": 0.04,
		"attack_reach_bonus": 0.09,
		"knockback_bonus": 10.0,
		"move_speed_bonus": 0.02,
		"throw_damage": 9.0,
		"skill_id": "arcane_echo",
		"skill_name": "Arcane Echo",
		"skill_description": "Treffer loesen magische Echo-Schlaege aus, die zusaetzlich einschlagen.",
	},
	"fragmented": {
		"atlas": Vector2i(4, 2),
		"display_name": "Fragmented Sword",
		"description": "Jede Kante der Klinge kann absplittern und weitere Treffer erzeugen.",
		"rarity": "rare",
		"attack_power_bonus": 5,
		"damage_bonus": 0.12,
		"crit_chance_bonus": 0.03,
		"crit_damage_bonus": 0.12,
		"attack_speed_bonus": 0.02,
		"attack_reach_bonus": 0.04,
		"knockback_bonus": 14.0,
		"move_speed_bonus": 0.01,
		"throw_damage": 9.0,
		"skill_id": "shardburst",
		"skill_name": "Shardburst",
		"skill_description": "Schwertsplitter brechen aus und verursachen mehrere kleine Zusatztreffer.",
	},
	"nature": {
		"atlas": Vector2i(5, 2),
		"display_name": "Nature Sword",
		"description": "Gruene Resonanz heilt Joey und laesst Dornen aus dem Boden schnellen.",
		"rarity": "uncommon",
		"attack_power_bonus": 3,
		"damage_bonus": 0.08,
		"crit_chance_bonus": 0.03,
		"crit_damage_bonus": 0.08,
		"attack_speed_bonus": 0.04,
		"attack_reach_bonus": 0.05,
		"knockback_bonus": 6.0,
		"move_speed_bonus": 0.03,
		"throw_damage": 7.0,
		"skill_id": "verdant_renewal",
		"skill_name": "Verdant Renewal",
		"skill_description": "Treffer heilen Joey und koennen Dornen-Schaden in der Naehe ausloesen.",
	},
	"justice": {
		"atlas": Vector2i(0, 3),
		"display_name": "Justice Sword",
		"description": "Eine ehrliche Klinge, die starke Gegner und frische Ziele besonders hart straft.",
		"rarity": "rare",
		"attack_power_bonus": 5,
		"damage_bonus": 0.14,
		"crit_chance_bonus": 0.04,
		"crit_damage_bonus": 0.12,
		"attack_speed_bonus": 0.01,
		"attack_reach_bonus": 0.05,
		"knockback_bonus": 16.0,
		"move_speed_bonus": 0.01,
		"throw_damage": 9.0,
		"skill_id": "judgement",
		"skill_name": "Judgement",
		"skill_description": "Bestraft Gegner mit hoher Lebensenergie und verstaerkt Finisher.",
	},
	"many": {
		"atlas": Vector2i(1, 3),
		"display_name": "Many Sword",
		"description": "Die Klinge scheint sich selbst zu vervielfaeltigen und in Serien zu schlagen.",
		"rarity": "epic",
		"attack_power_bonus": 4,
		"damage_bonus": 0.12,
		"crit_chance_bonus": 0.04,
		"crit_damage_bonus": 0.1,
		"attack_speed_bonus": 0.09,
		"attack_reach_bonus": 0.04,
		"knockback_bonus": 8.0,
		"move_speed_bonus": 0.03,
		"throw_damage": 8.0,
		"skill_id": "mirror_strike",
		"skill_name": "Mirror Strike",
		"skill_description": "Erschafft Nachbilder, die weitere Treffer auf dasselbe oder ein nahes Ziel legen.",
	},
	"glowing": {
		"atlas": Vector2i(2, 3),
		"display_name": "Glowing Sword",
		"description": "Eine strahlende Klinge, die mit Joeys Licht-Faehigkeit gemeinsam aufblueht.",
		"rarity": "epic",
		"attack_power_bonus": 4,
		"damage_bonus": 0.13,
		"crit_chance_bonus": 0.04,
		"crit_damage_bonus": 0.13,
		"attack_speed_bonus": 0.05,
		"attack_reach_bonus": 0.05,
		"knockback_bonus": 10.0,
		"move_speed_bonus": 0.02,
		"throw_damage": 9.0,
		"skill_id": "radiant_pulse",
		"skill_name": "Radiant Pulse",
		"skill_description": "Leuchtende Angriffe senden eine Zusatzwelle aus, besonders stark waehrend Glow aktiv ist.",
	},
	"dragon_slayer": {
		"atlas": Vector2i(3, 3),
		"display_name": "Dragon Slayer",
		"description": "Eine Jagdklinge fuer gewaltige Ziele und dicke Lebensbalken.",
		"rarity": "legendary",
		"attack_power_bonus": 8,
		"damage_bonus": 0.2,
		"crit_chance_bonus": 0.05,
		"crit_damage_bonus": 0.16,
		"attack_speed_bonus": -0.01,
		"attack_reach_bonus": 0.08,
		"knockback_bonus": 22.0,
		"move_speed_bonus": 0.0,
		"throw_damage": 12.0,
		"skill_id": "slayer_mark",
		"skill_name": "Slayer Mark",
		"skill_description": "Verursacht viel Bonus-Schaden gegen Gegner mit hoher Maximal-Lebenskraft.",
	},
	"guardian": {
		"atlas": Vector2i(4, 3),
		"display_name": "Guardian Sword",
		"description": "Ein beschuetzendes Schwert, das Joey waehrend des Kampfes abschirmt.",
		"rarity": "rare",
		"attack_power_bonus": 4,
		"damage_bonus": 0.11,
		"crit_chance_bonus": 0.03,
		"crit_damage_bonus": 0.09,
		"attack_speed_bonus": 0.01,
		"attack_reach_bonus": 0.04,
		"knockback_bonus": 14.0,
		"move_speed_bonus": 0.0,
		"throw_damage": 8.0,
		"skill_id": "warding_edge",
		"skill_name": "Warding Edge",
		"skill_description": "Treffer bauen eine sichtbare Schutzschicht auf und geben Stabilitaet.",
	},
	"sinister": {
		"atlas": Vector2i(5, 3),
		"display_name": "Sinister Sword",
		"description": "Dunkle Kanten belohnen tueckische Treffer und kalte Erstoessung.",
		"rarity": "epic",
		"attack_power_bonus": 5,
		"damage_bonus": 0.15,
		"crit_chance_bonus": 0.07,
		"crit_damage_bonus": 0.18,
		"attack_speed_bonus": 0.03,
		"attack_reach_bonus": 0.03,
		"knockback_bonus": 10.0,
		"move_speed_bonus": 0.03,
		"throw_damage": 10.0,
		"skill_id": "shadow_fang",
		"skill_name": "Shadow Fang",
		"skill_description": "Der erste Treffer nach kurzer Ruhezeit wird zu einem besonders boesen Stich.",
	},
	"jeweled": {
		"atlas": Vector2i(0, 4),
		"display_name": "Jeweled Sword",
		"description": "Juwelen leiten Energie in kurze Funkenexplosionen und saubere Crits.",
		"rarity": "rare",
		"attack_power_bonus": 4,
		"damage_bonus": 0.11,
		"crit_chance_bonus": 0.07,
		"crit_damage_bonus": 0.14,
		"attack_speed_bonus": 0.03,
		"attack_reach_bonus": 0.04,
		"knockback_bonus": 8.0,
		"move_speed_bonus": 0.02,
		"throw_damage": 8.0,
		"skill_id": "gem_burst",
		"skill_name": "Gem Burst",
		"skill_description": "Crits explodieren in Splittern und treffen das Hauptziel ein zweites Mal.",
	},
	"ocean": {
		"atlas": Vector2i(1, 4),
		"display_name": "Ocean Sword",
		"description": "Eine fluessige Schneide, die Wasserwellen durch den Nahkampf zieht.",
		"rarity": "rare",
		"attack_power_bonus": 4,
		"damage_bonus": 0.12,
		"crit_chance_bonus": 0.03,
		"crit_damage_bonus": 0.1,
		"attack_speed_bonus": 0.04,
		"attack_reach_bonus": 0.08,
		"knockback_bonus": 12.0,
		"move_speed_bonus": 0.03,
		"throw_damage": 8.0,
		"skill_id": "tidal_cut",
		"skill_name": "Tidal Cut",
		"skill_description": "Wasserartige Schockwellen treffen Gegner in einer Linie und heilen Joey im Wasser.",
	},
	"flower": {
		"atlas": Vector2i(2, 4),
		"display_name": "Flower Sword",
		"description": "Bluetenblaetter tanzen um die Klinge und setzen sanfte, aber konstante Procs frei.",
		"rarity": "uncommon",
		"attack_power_bonus": 3,
		"damage_bonus": 0.08,
		"crit_chance_bonus": 0.05,
		"crit_damage_bonus": 0.08,
		"attack_speed_bonus": 0.06,
		"attack_reach_bonus": 0.04,
		"knockback_bonus": 6.0,
		"move_speed_bonus": 0.03,
		"throw_damage": 7.0,
		"skill_id": "petal_dance",
		"skill_name": "Petal Dance",
		"skill_description": "Lange Trefferfolgen erzeugen Bluetenwirbel und kleine Heilimpulse.",
	},
	"royal": {
		"atlas": Vector2i(3, 4),
		"display_name": "Royal Sword",
		"description": "Eine herrschaftliche Klinge mit ausgewogenem Druck und stilvollen Finishs.",
		"rarity": "rare",
		"attack_power_bonus": 5,
		"damage_bonus": 0.13,
		"crit_chance_bonus": 0.05,
		"crit_damage_bonus": 0.12,
		"attack_speed_bonus": 0.02,
		"attack_reach_bonus": 0.05,
		"knockback_bonus": 14.0,
		"move_speed_bonus": 0.02,
		"throw_damage": 9.0,
		"skill_id": "royal_decree",
		"skill_name": "Royal Decree",
		"skill_description": "Finisher erhalten einen starken Bonus und loesen einen kleinen Hofstaat-Nachhieb aus.",
	},
	"ceremony": {
		"atlas": Vector2i(4, 4),
		"display_name": "Ceremony Sword",
		"description": "Ein feines Ritualschwert fuer kontrollierte Praezision und saubere Timings.",
		"rarity": "uncommon",
		"attack_power_bonus": 3,
		"damage_bonus": 0.09,
		"crit_chance_bonus": 0.05,
		"crit_damage_bonus": 0.1,
		"attack_speed_bonus": 0.07,
		"attack_reach_bonus": 0.05,
		"knockback_bonus": 8.0,
		"move_speed_bonus": 0.02,
		"throw_damage": 7.0,
		"skill_id": "ritual_flow",
		"skill_name": "Ritual Flow",
		"skill_description": "Verkuerzt die Erholung zwischen Combo-Schritten und stabilisiert den Rhythmus.",
	},
	"ancient": {
		"atlas": Vector2i(5, 4),
		"display_name": "Ancient Sword",
		"description": "Eine uralte Klinge, in der ein langsamer, gewaltiger Nachhall lebt.",
		"rarity": "legendary",
		"attack_power_bonus": 7,
		"damage_bonus": 0.19,
		"crit_chance_bonus": 0.04,
		"crit_damage_bonus": 0.16,
		"attack_speed_bonus": 0.0,
		"attack_reach_bonus": 0.1,
		"knockback_bonus": 20.0,
		"move_speed_bonus": 0.0,
		"throw_damage": 11.0,
		"skill_id": "ancient_echo",
		"skill_name": "Ancient Echo",
		"skill_description": "Gelegentlich rollt ein uralter Nachschlag als breite Schockwelle durch den Kampf.",
	},
}

static var _item_cache: Dictionary = {}


static func has_weapon(item_name: String) -> bool:
	return item_name == DEFAULT_SWORD_NAME or SWORD_DEFS.has(item_name)


static func get_default_weapon() -> InvItem:
	return get_item(DEFAULT_SWORD_NAME)


static func get_all_sword_names() -> Array[String]:
	var names: Array[String] = []
	for item_name in SHOP_ORDER:
		names.append(String(item_name))
	return names


static func get_shop_offers() -> Array[Dictionary]:
	var offers: Array[Dictionary] = []
	for item_name in get_all_sword_names():
		offers.append({
			"item_name": item_name,
			"price": {"currency": "copper", "amount": 0},
			"featured": false,
		})
	return offers


static func get_definition(item_name: String) -> Dictionary:
	if item_name == DEFAULT_SWORD_NAME:
		return STARTER_SWORD.duplicate(true)
	if not SWORD_DEFS.has(item_name):
		return {}
	return (SWORD_DEFS[item_name] as Dictionary).duplicate(true)


static func get_item(item_name: String) -> InvItem:
	if _item_cache.has(item_name):
		return _item_cache[item_name] as InvItem

	var definition := get_definition(item_name)
	if definition.is_empty():
		return null

	var item := InvItem.new()
	item.name = item_name
	item.display_name = String(definition.get("display_name", item_name.replace("_", " ").capitalize()))
	item.description = String(definition.get("description", ""))
	item.texture = _make_atlas_texture(definition.get("atlas", Vector2i.ZERO) as Vector2i)
	item.item_type = "weapon"
	item.equip_slot = "weapon"
	item.rarity = String(definition.get("rarity", "common"))
	item.stack_size = 1
	item.attack_power_bonus = int(definition.get("attack_power_bonus", 0))
	item.damage_bonus = float(definition.get("damage_bonus", 0.0))
	item.crit_chance_bonus = float(definition.get("crit_chance_bonus", 0.0))
	item.crit_damage_bonus = float(definition.get("crit_damage_bonus", 0.0))
	item.attack_speed_bonus = float(definition.get("attack_speed_bonus", 0.0))
	item.attack_reach_bonus = float(definition.get("attack_reach_bonus", 0.0))
	item.knockback_bonus = float(definition.get("knockback_bonus", 0.0))
	item.move_speed_bonus = float(definition.get("move_speed_bonus", 0.0))
	item.throw_damage = float(definition.get("throw_damage", 0.0))
	item.skill_id = String(definition.get("skill_id", ""))
	item.skill_name = String(definition.get("skill_name", ""))
	item.skill_description = String(definition.get("skill_description", ""))
	_item_cache[item_name] = item
	return item


static func _make_atlas_texture(atlas_position: Vector2i) -> AtlasTexture:
	var atlas := AtlasTexture.new()
	atlas.atlas = SWORD_SHEET
	atlas.region = Rect2(
		float(atlas_position.x * CELL_SIZE.x),
		float(atlas_position.y * CELL_SIZE.y),
		float(CELL_SIZE.x),
		float(CELL_SIZE.y)
	)
	return atlas
